version: '2'
services:
  server:
    build:
      context: ../
      args:
        settings: 'django_starterkit.settings'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ../:/usr/src/app/

    environment:
      DJANGO_SETTINGS_MODULE: 'django_starterkit.docker'
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - redis

  cadvisor:
    restart: always
    image: google/cadvisor:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
  # Redis
  redis:
    image: redis:2.8.19
    hostname: redis
    expose:
      - "6379"
