version: '2'
services:
  server:
    image: sitmena/django-starterkit
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ../:/usr/src/app/
      - C:\Users\AhmadigA\django-builder\django-builder\sit_builder:/usr/local/lib/python3.5/site-packages/sit_builder/

    environment:
      DJANGO_SETTINGS_MODULE: 'django_starterkit.docker'
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

  cadvisor:
    restart: always
    image: google/cadvisor:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
